### Fetching all data
GET http://localhost:3000/reports

### Sync data from Spreatheets
POST http://localhost:3000/reports/sync

### Simulate Webhook
POST http://localhost:3000/reports/webhook
Content-Type: application/json

{
  "event": "sheet_updated"
}
